### ISSUE TITLE
Is there a way to disable the spinner/transition?

### ISSUE THREAD

**Issue by triplumix** [guonanci/react-images-viewer#17]
I would like to go straight to the next image, without showing the spinner. 
I assume that "preloadNextImg" will load the next image and then I just need to show the next image (without the spinner), or at least to speed up the animation.

**Comment by guonanci** [comment]
Since version v1.6.3, `spinnerDisabled` prop can be used.  The `preloadNextImg` cache feature has built in ImgsViewer.js to speed up the animation. If the Component doesnt konw the direction you browse images, it will load the first image a little slowly, but just limited to the first time, Once the last browse direction is known, `preloadNextImg` will work properly. I'd you to ask me if you still have a trouble.
